// English begins ...
export const engUnits = {
  bag: ["bag", "bags"],
  box: ["box"],
  can: ["can"],
  cup: ["cup", "c", "c.", "C", "Cups"],
  clove: ["clove"],
  gallon: ["gallon", "gal"],
  ounce: ["ounce", "oz", "oz."],
  pint: ["pint", "pt", "pts", "pt."],
  pound: ["pound", "lb", "lb.", "lbs", "lbs.", "Lb", "Lbs"],
  quart: ["quart", "qt", "qt.", "qts", "qts."],
  tablespoon: ["tbs", "tbsp", "tbspn", "T", "T.", "Tablespoons", "Tablespoon"],
  teaspoon: ["teaspoon", "tsp", "tspn", "t", "t."],
  gram: ["gram", "g", "g."],
  kilogram: ["kilogram", "kg", "kg.", "Kg", "Kg."],
  liter: ["liter", "l", "l.", "lt", "Lt", "LT", "L", "L."],
  milligram: ["milligram", "mg", "mg."],
  milliliter: ["milliliter", "ml", "ml.", "mL", "mL."],
  package: ["package", "pkg", "pkgs"],
  stick: ["stick", "sticks"],
  piece: ["piece", "pcs", "pcs."],
  pinch: ["pinch"],
  small: ["Small"],
  slice: ["slice"],
  medium: ["Medium"],
  large: ["large", "Large"],
} as { [key: string]: string[] };

export const engPluralUnits = {
  cup: "cups",
  gallon: "gallons",
  ounce: "ounces",
  pint: "pints",
  pound: "pounds",
  quart: "quarts",
  tablespoon: "tablespoons",
  teaspoon: "teaspoons",
  gram: "grams",
  kilogram: "kilograms",
  liter: "liters",
  milligram: "milligrams",
  milliliter: "milliliters",
  clove: "cloves",
  bag: "bags",
  box: "boxes",
  pinch: "pinches",
  can: "cans",
  slice: "slices",
  piece: "pieces",
} as { [key: string]: string };

export const engNameToSymbol = {
  cup: "c",
  gallon: "gal",
  ounce: "oz",
  pint: "pt",
  pound: "lb",
  quart: "qt",
  tablespoon: "tbs",
  teaspoon: "tsp",
  gram: "g",
  kilogram: "kg",
  liter: "lt",
  milligram: "mg",
  milliliter: "ml",
  clove: "",
  bag: "",
  box: "",
  pinch: "",
  can: "",
  slice: "",
  piece: "",
} as { [key: string]: string };

export const engPreposition = ["of"];
// fin english

// Italian begins
export const itaUnits = {
  barattolo: ["barattolo", "barattoli"],
  bicchiere: ["bicchiere"],
  bottiglia: ["bottiglie", "bottiglia"],
  bustina: ["bustina", "bustine"],
  cubetto: ["cubetto", "cubetti"],
  cucchiaio: ["cucchiai", "cucchiaio"],
  cucchiaino: ["cucchiaini", "cucchiaino"],
  confezione: ["confezioni", "confezione"],
  grammo: ["g", "g\\.", "gr\\.", "gr", "grammi", "grammo"],
  chilogrammo: [
    "kg.",
    "kg",
    "kilogrammo",
    "chilogrammi",
    "kilogrammo",
    "chilogrammo",
  ],
  fetta: ["fetta", "fette"],
  fettina: ["fettina", "fettine"],
  fogliolina: ["fogliolina", "foglioline"],
  foglia: ["foglie", "foglia"],
  foglio: ["fogli", "foglio"],
  gambo: ["gambo", "gambi"],
  litro: ["l\\.", "l", "lt", "litro"],
  mazzo: ["mazzo", "mazzi"],
  mazzetto: ["Mazzetto", "mazzetti", "mazzetto"],
  lattina: ["Lattina", "lattina"],
  milligrammo: ["mg.", "mg", "milligrammo"],
  millilitro: ["ml", "ml\\.", "millilitro"],
  panetto: ["Panetto", "panetti", "panetto"],
  pacco: ["pkg", "pkgs", "pacchetto", "pacco"],
  pezzo: ["pezzo", "pcs", "pcs.", "pezzi"],
  pizzico: ["pizzico", "pizzichi"],
  tazza: ["tazza", "tazzina", "tazzine"],
  sacco: ["sacco", "sacchi"],
  spicchio: ["spicchio", "spicchi"],
  scatola: ["scatola", "scatole"],
  vasetto: ["vasetto", "vasetti"],
  filo: ["filo"],
  ciuffo: ["ciuffo"],
  scatoletta: ["scatoletta"],
  manciata: ["manciata"],
  rametto: ["rametto", "rametti"],
  rotolo: ["rotolo"],
  pugno: ["pugno", "pugni"],
  bicchierino: ["bicchierino"],

  //noce: ['noce'],
} as { [key: string]: string[] };

export const itaPluralUnits = {
  barattolo: "barattoli",
  bicchiere: "bicchieri",
  bustina: "bustine",
  bottiglia: "bottiglie",
  cubetto: "cubetti",
  gambo: "gambi",
  tazza: "tazze",
  quarto: "quarti",
  cucchiaio: "cucchiai",
  cucchiaino: "cucchiaini",
  confezione: "confezioni",
  grammo: "grammi",
  chilogrammo: "chilogrammi",
  litro: "litri",
  milligrammo: "milligrammi",
  millilitro: "millilitri",
  spicchio: "spicchi",
  scatola: "scatole",
  pizzico: "pizzichi",
  lattina: "lattine",
  fetta: "fette",
  fettina: "fettine",
  pezzo: "pezzi",
  panetto: "panetti",
  foglio: "fogli",
  fogliolina: "foglioline",
  foglia: "foglie",
  mazzo: "mazzi",
  mazzetto: "mazzetti",
  vasetto: "vasetti",
  filo: "fili",
  ciuffo: "ciuffi",
  sacco: "sacchi",
  scatoletta: "scatolette",
  manciata: "manciate",
  rametto: "rametti",
  rotolo: "rotoli",
  bicchierino: "bicchierini",
  pugno: "pugni",
  //noce: 'noci'
} as { [key: string]: string };

export const itaNameToSymbol = {
  bicchiere: "",
  bustina: "",
  cubetto: "",
  gambo: "",
  tazza: "",
  quarto: "",
  cucchiaio: "",
  spicchio: "",
  scatola: "",
  pizzico: "",
  lattina: "",
  fetta: "",
  pezzo: "",
  panetto: "",
  foglia: "",
  mazzetto: "",
  manciata: "",
  vasetto: "",
  grammo: "g",
  cucchiaino: "cc",
  chilogrammo: "kg",
  litro: "lt",
  milligrammo: "mg",
  millilitro: "ml",
} as { [key: string]: string };

export const itaPreposition = ["di", "d'"];

// Italian ends

// French begins

export const fraUnits = {
  tasse: ["tasse", "tasses"],
  cuillièreSoupe: [
    "cuillières à soupe",
    "cuillière à soupe",
    "c.à soupe",
    "c. à s.",
    "c. à soupe",
    "c à soupe",
    "càs.",
    "c à s",
    "c.à s.",
    "c.à.s",
  ],
  cuillièreCafé: [
    "cuillières à café",
    "cuillière à café",
    "c à café",
    "c.à café",
    "c. à café",
    "c.à c.",
    "c. à c.",
    "c.à.c",
    "càc.",
    "c à c",
    "càc",
  ],
  cuillièreThé: [
    "cuillières à thé",
    "cuillière à thé",
    "c à thé",
    "c.à thé",
    "c. à thé",
    "c.à t.",
    "c. à t.",
    "càt.",
    "c à t",
    "càt",
    "c.à.t",
  ],
  bocal: ["bocal", "bocaux"],
  verre: ["verre", "verres"],
  bouteille: ["bouteille", "bouteilles"],
  sachet: ["sachet", "sachets"],
  cube: ["cube", "cubes"],
  gramme: ["g", "g.", "gr.", "gr", "grammes", "gramme"],
  kilogramme: ["kg.", "kg", "kilogramme", "kilogrammes"],
  tranche: ["tranche", "tranches"],
  trancheFine: ["fine tranche", "fines tranches"],
  petiteFeuille: ["petite feuille", "petites feuilles"],
  feuille: ["feuille", "feuilles"],
  tige: ["tige", "tiges"],
  litre: ["l.", "l", "lt", "litre"],
  bouquet: ["bouquet", "bouquets"],
  petitBouquet: ["petit bouquet", "petits bouquets"],
  canette: ["canette, canettes"],
  milligramme: ["mg.", "mg", "milligramme", "milligrammes"],
  millilitre: ["ml", "ml.", "millilitre"],
  bloc: ["bloc", "blocs"],
  paquet: ["pkg", "pkgs", "paquet", "paquets"],
  morceau: ["morceau", "morceaux"],
  pincée: ["pincée", "pincées"],
  petiteTasse: ["petite tasse", "petites tasses"],
  sac: ["sac", "sacs"],
  gousse: ["gousse", "gousses"],
  boîte: ["boîte", "boîtes"],
  petitPot: ["petit pot", "petits pots"],
  fil: ["fil"],
  touffe: ["touffe"],
  petiteBoîte: ["petite boîte"],
  petiteBranche: ["petite branche", "petites branches"],
  branche: ["branche", "branches"],
  rouleau: ["rouleau"],
  poignée: ["poignée", "poignées"],
  petitVerre: ["petit verre", "petits verres"],
  petit: ["petit", "petits"],
  grand: ["grand", "grands"],
  moyen: ["moyen", "moyens"],
  clou: ["clou", "clous"],
  copeau: ["copeau", "copeaux"],
  noix: ["noix"],
} as { [key: string]: string[] };

export const fraPluralUnits = {
  bocal: "bocaux",
  verre: "verres",
  bouteille: "bouteilles",
  sachet: "sachets",
  cube: "cubes",
  gramme: "grammes",
  kilogramme: "kilogrammes",
  tranche: "tranches",
  trancheFine: "fines tranches",
  petiteFeuille: "petites feuilles",
  feuille: "feuilles",
  tige: "tiges",
  litre: "litres",
  bouquet: "bouquets",
  petitBouquet: "petits bouquets",
  canette: "canettes",
  milligramme: "milligrammes",
  millilitre: "millilitres",
  bloc: "blocs",
  paquet: "paquets",
  morceau: "morceaux",
  pincée: "pincées",
  tasse: "tasses",
  petiteTasse: "petites tasses",
  sac: "sacs",
  gousse: "gousses",
  boîte: "boîtes",
  petitPot: "petits pots",
  fil: "fils",
  touffe: "touffes",
  petiteBoîte: "petites boîtes",
  petiteBranche: "petites branches",
  branche: "branches",
  rouleau: "rouleaux",
  poignée: "poignées",
  petitVerre: "petits verres",
  petit: "petits",
  grand: "grands",
  moyen: "moyens",
  clou: "clous",
  copeau: "copeaux",
  noix: "noix",
} as { [key: string]: string };

export const fraNameToSymbol = {
  verre: "",
  sachet: "",
  cube: "",
  tige: "",
  tasse: "",
  quart: "",
  girofle: "",
  pinçée: "",
  boite: "",
  tranche: "",
  pièce: "pce",
  morceau: "",
  pain: "",
  miche: "",
  feuille: "",
  bouquet: "",
  poignée: "",
  pot: "",
  gramme: "g.",
  cuillière: "cc",
  kilogramme: "kg",
  litre: "l",
  décilitre: "dl",
  centilitre: "cl",
  milligramme: "mg",
  millilitre: "ml",
} as { [key: string]: string };

export const fraPreposition = ["de", "d'"];

// French ends

export const unitsMap = new Map();
unitsMap.set("eng", [
  engUnits,
  engPluralUnits,
  engPreposition,
  engNameToSymbol,
]);
unitsMap.set("ita", [
  itaUnits,
  itaPluralUnits,
  itaPreposition,
  itaNameToSymbol,
]);
unitsMap.set("fra", [
  fraUnits,
  fraPluralUnits,
  fraPreposition,
  fraNameToSymbol,
]);
